export const INITIAL_DOCTORS = [
  {
    firstName: 'M Zafar',
    lastName: 'Iqbal',
    email: 'zafar.iqbal@lalamedical.com',
    phone: '+92 300 0000001',
    qualification: 'MBBS, FCPS, MME',
    specialization: 'Pediatric Surgeon / CEO',
    experience: 20,
    gender: 'Male',
    consultationFee: 1000,
    registrationNumber: '33791-P',
    signatureText: 'Prof Dr. M Zafar Iqbal - Pediatric Surgeon / CEO',
    availability: [
      { dayOfWeek: 'Monday', startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 'Wednesday', startTime: '09:00 AM', endTime: '02:00 PM' },
    ],
  },
  {
    firstName: 'Shumaila',
    lastName: 'Irum',
    email: 'shumaila.irum@lalamedical.com',
    phone: '+92 300 0000002',
    qualification: 'MBBS, MME, M Phil (Physiology)',
    specialization: 'APWMO / MS',
    experience: 12,
    gender: 'Female',
    consultationFee: 500,
    registrationNumber: '41229-P',
    signatureText: 'Dr. Shumaila Irum - APWMO / MS',
    availability: [
      { dayOfWeek: 'Tuesday', startTime: '09:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 'Thursday', startTime: '09:00 AM', endTime: '02:00 PM' },
    ],
  },
  {
    firstName: 'Noor Ahmed',
    lastName: 'Niazi',
    email: 'noor.niazi@lalamedical.com',
    phone: '+92 300 0000003',
    qualification: 'MBBS, FCPS',
    specialization: 'Consultant Surgeon',
    experience: 15,
    gender: 'Male',
    consultationFee: 1000,
    registrationNumber: '15228–P',
    signatureText: 'Dr. Noor Ahmed Niazi - Consultant Surgeon',
    availability: [
      { dayOfWeek: 'Monday', startTime: '11:00 AM', endTime: '04:00 PM' },
      { dayOfWeek: 'Friday', startTime: '04:00 PM', endTime: '08:00 PM' },
    ],
  },
  {
    firstName: 'Afsheen',
    lastName: 'Asif',
    email: 'afsheen.asif@lalamedical.com',
    phone: '+92 300 0000004',
    qualification: 'MBBS, MCPS',
    specialization: 'Consultant Gynecologist',
    experience: 10,
    gender: 'Female',
    consultationFee: 1000,
    registrationNumber: '50192-S',
    signatureText: 'Dr. Afsheen Asif - Consultant Gynecologist',
    availability: [
      { dayOfWeek: 'Monday', startTime: '10:00 AM', endTime: '03:00 PM' },
      { dayOfWeek: 'Wednesday', startTime: '10:00 AM', endTime: '03:00 PM' },
    ],
  },
  {
    firstName: 'Mohtmam',
    lastName: 'Nazir',
    email: 'mohtmam.nazir@lalamedical.com',
    phone: '+92 300 0000005',
    qualification: 'MBBS, FCPS',
    specialization: 'Consultant General & Laparoscopic Surgeon',
    experience: 14,
    gender: 'Male',
    consultationFee: 1000,
    registrationNumber: '53225-P',
    signatureText: 'Dr. Mohtmam Nazir - Consultant Surgeon',
    availability: [
      { dayOfWeek: 'Tuesday', startTime: '10:00 AM', endTime: '03:00 PM' },
      { dayOfWeek: 'Thursday', startTime: '10:00 AM', endTime: '03:00 PM' },
    ],
  },
  {
    firstName: 'Tahir',
    lastName: 'Mehmood',
    email: 'tahir.mehmood@lalamedical.com',
    phone: '+92 300 0000006',
    qualification: 'MBBS, FCPS',
    specialization: 'Consultant Surgeon',
    experience: 16,
    gender: 'Male',
    consultationFee: 1000,
    registrationNumber: '29761-S',
    signatureText: 'Dr. Tahir Mehmood - Consultant Surgeon',
    availability: [
      { dayOfWeek: 'Wednesday', startTime: '02:00 PM', endTime: '06:00 PM' },
      { dayOfWeek: 'Saturday', startTime: '09:00 AM', endTime: '01:00 PM' },
    ],
  },
  {
    firstName: 'Anees Ur',
    lastName: 'Rehman',
    email: 'anees.rehman@lalamedical.com',
    phone: '+92 300 0000007',
    qualification: 'MBBS, DLO, FCPS',
    specialization: 'Consultant ENT Surgeon',
    experience: 11,
    gender: 'Male',
    consultationFee: 1000,
    registrationNumber: '32011-P',
    signatureText: 'Dr. Anees Ur Rehman - Consultant ENT Surgeon',
    availability: [
      { dayOfWeek: 'Monday', startTime: '04:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 'Thursday', startTime: '04:00 PM', endTime: '08:00 PM' },
    ],
  },
  {
    firstName: 'Amir',
    lastName: 'Hameed',
    email: 'amir.hameed@lalamedical.com',
    phone: '+92 300 0000008',
    qualification: 'MBBS, FCPS',
    specialization: 'Consultant Orthopedic Surgeon',
    experience: 13,
    gender: 'Male',
    consultationFee: 1000,
    registrationNumber: '49132-P',
    signatureText: 'Dr. Amir Hameed - Consultant Orthopedic Surgeon',
    availability: [
      { dayOfWeek: 'Tuesday', startTime: '04:00 PM', endTime: '08:00 PM' },
      { dayOfWeek: 'Friday', startTime: '04:00 PM', endTime: '08:00 PM' },
    ],
  },
  {
    firstName: 'Sajid',
    lastName: 'Ghafoor',
    email: 'sajid.ghafoor@lalamedical.com',
    phone: '+92 300 0000009',
    qualification: 'MBBS, DMRT',
    specialization: 'Consultant Oncologist',
    experience: 15,
    gender: 'Male',
    consultationFee: 1000,
    registrationNumber: '42801-P',
    signatureText: 'Dr. Sajid Ghafoor - Consultant Oncologist',
    availability: [
      { dayOfWeek: 'Wednesday', startTime: '09:00 AM', endTime: '01:00 PM' },
    ],
  },
  {
    firstName: 'Syed Abbas',
    lastName: 'Rasool',
    email: 'abbas.rasool@lalamedical.com',
    phone: '+92 300 0000010',
    qualification: 'MBBS, DIP CARD (NICVD)',
    specialization: 'Consultant Cardiologist',
    experience: 18,
    gender: 'Male',
    consultationFee: 1000,
    registrationNumber: '80232-P',
    signatureText: 'Dr. Syed Abbas Rasool - Consultant Cardiologist',
    availability: [
      { dayOfWeek: 'Monday', startTime: '09:00 AM', endTime: '01:00 PM' },
      { dayOfWeek: 'Thursday', startTime: '09:00 AM', endTime: '01:00 PM' },
    ],
  },
  {
    firstName: 'Asif',
    lastName: 'Hussain',
    email: 'asif.hussain@lalamedical.com',
    phone: '+92 300 0000011',
    qualification: 'MBBS, MCPS',
    specialization: 'Consultant Anesthetist',
    experience: 9,
    gender: 'Male',
    consultationFee: 1000,
    registrationNumber: '46493-S',
    signatureText: 'Dr. Asif Hussain - Consultant Anesthetist',
    availability: [
      { dayOfWeek: 'Monday', startTime: '08:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 'Wednesday', startTime: '08:00 AM', endTime: '02:00 PM' },
      { dayOfWeek: 'Friday', startTime: '08:00 AM', endTime: '02:00 PM' },
    ],
  },
];
