export const INITIAL_PATIENTS = [
  {
    mrNumber: 'MRN-202607-0001',
    firstName: 'Muhammad',
    lastName: 'Ali',
    fatherHusbandName: 'Tariq Mahmood',
    gender: 'Male',
    dateOfBirth: '1988-04-12',
    age: 38,
    maritalStatus: 'Married',
    mobileNumber: '03001234567',
    alternateMobileNumber: '03217654321',
    address: 'House #45, Street 4, Satellite Town',
    city: 'Rahim Yar Khan',
    cnic: '38403-1234567-1',
    bloodGroup: 'B+',
    allergies: 'Penicillin',
    chronicDiseases: 'Hypertension',
    remarks: 'Regular Patient',
  },
  {
    mrNumber: 'MRN-202607-0002',
    firstName: 'Fatima',
    lastName: 'Noor',
    fatherHusbandName: 'Ahmed Raza',
    gender: 'Female',
    dateOfBirth: '1995-09-25',
    age: 30,
    maritalStatus: 'Single',
    mobileNumber: '03129876543',
    alternateMobileNumber: null,
    address: 'Plot 12, Block B, University Road',
    city: 'Rahim Yar Khan',
    cnic: '38403-9876543-2',
    bloodGroup: 'O+',
    allergies: null,
    chronicDiseases: null,
    remarks: null,
  },
  {
    mrNumber: 'MRN-202607-0003',
    firstName: 'Usman',
    lastName: 'Ghani',
    fatherHusbandName: 'Abdul Ghani',
    gender: 'Male',
    dateOfBirth: '1976-11-05',
    age: 49,
    maritalStatus: 'Married',
    mobileNumber: '03335557788',
    alternateMobileNumber: null,
    address: 'Street #9, Civil Lines',
    city: 'Rahim Yar Khan',
    cnic: '38403-5557788-3',
    bloodGroup: 'A+',
    allergies: 'Dust & Pollen',
    chronicDiseases: 'Asthma',
    remarks: null,
  },
];
